services:
  derper:
    image: derp
    pull_policy: if_not_present
    container_name: derper
    restart: always
    # network_mode: "host"
    volumes:
      - ./certs:/app/certs # 挂载证书目录
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock # DERP_VERIFY_CLIENTS true 时容器需要访问 Tailscale 的 Local API
    ports:
      - 443:443 # DERP TLS 端口
      - 3478:3478/udp # STUN UDP端口
    environment:
      - DERP_DOMAIN=<domain/ip> # 替换为你的域名或IP
      - DERP_CERT_DIR=/app/certs # 证书目录
      - DERP_CERT_MODE=manual # 使用手动模式
      - DERP_VERIFY_CLIENTS=true # 仅允许Tailscale授权节点
      - DERP_HTTP_PORT=-1 # 禁用HTTP
