services:
  derper:
    image: derp
    pull_policy: if_not_present
    container_name: derper
    restart: always
    # network_mode: "host"
    volumes:
      - ./certs:/app/certs # 挂载证书目录
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock # DERP_VERIFY_CLIENTS true 时容器需要访问 Tailscale 的 Local API
    ports:
      - 443:443 # DERP TLS 端口
      - ${DERP_STUN_PORT:-3478}:${DERP_STUN_PORT:-3478}/udp # STUN UDP端口
    env_file:
      - .env
    command:
      - /app/derper
      - --hostname=${DERP_DOMAIN}
      - --a=${DERP_ADDR}
      - --http-port=${DERP_HTTP_PORT}
      - --certmode=${DERP_CERT_MODE}
      - --certdir=${DERP_CERT_DIR}
      - --stun=${DERP_STUN}
      - --stun-port=${DERP_STUN_PORT}
      - --verify-clients=${DERP_VERIFY_CLIENTS}
      - --verify-client-url=${DERP_VERIFY_CLIENT_URL}
